### ISSUE TITLE
Include FAIR aspects from CRAN checklist

### ISSUE THREAD

**Issue by katrinleinweber** [TIBHannover/FAIR-R#20]
- [ ] refer to https://cran.r-project.org/web/packages/submission_checklist.html
- [ ] Add a challenge about inserting a [`<doi:…>`](https://cran.r-project.org/web/packages/submission_checklist.html)
- [ ] if `usethis` auto-inserts ORCiD, remove that challenge & only [explain briefly](https://orcid.org/)
